---
title: "Class Materials"
output: 
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
    theme: cosmo
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Day 1 1/23
[Intro slides](https://docs.google.com/presentation/d/1leuqEq3fMsP4chlN1tfmopWeNAF2EsITLIRQk5ssXMU/edit?usp=sharing)  
Read: Reproducible Research - Ch 1 (Introduction) and Ch 6 (Building Towards a Future)

### Day 2 1/28
[Slides](https://docs.google.com/presentation/d/1RgwBEe16PYOgCUgy8cvXUtFe7mG_Y5XuZfvbwrxWZ3c/edit?usp=sharing)  
[R materials](Oz_fires_DC_remix.html)  
[Other tutorials for R](https://rstudio.cloud/learn/primers)

### Day 3 1/30
R: see above  
Read: [R For Data Science ch. 12.1 - 12.2, 12.7](https://r4ds.had.co.nz/tidy-data.html)  
Read: [Tidy Data Paper](http://www.jstatsoft.org/v59/i10/paper)  

### Day 4 2/4
Read: [R For Data Science ch. 12.3, 12.6](https://r4ds.had.co.nz/tidy-data.html)  
Read: [Data Organization in Spreadsheets](https://www.tandfonline.com/doi/full/10.1080/00031305.2017.1375989)

### Day 5 2/6
[Met Museum Data (messy example)](https://github.com/metmuseum/openaccess)  
Read: [Best Practices for Google Sheets](https://matthewlincoln.net/2018/03/26/best-practices-for-using-google-sheets-in-your-data-project.html)  
[Data issues from class](https://docs.google.com/document/d/1epE3unqsXIsngYSXaGuqolCpQZPpU9SQQcMuXswcEh0/edit?usp=sharing)

### Day 6 2/11
Tutorial: [Joining data](https://datacarpentry.org/R-ecology-lesson/05-r-and-databases.html#complex-database-queries)

### Day 7 2/13
Read: [R For Data Science ch. 19.1-19.3, 19.5-19.7](https://r4ds.had.co.nz/functions.html)  
Function tutorials: [Software Carpentry lesson 1](https://swcarpentry.github.io/r-novice-inflammation/02-func-R/)
and [lesson 2](https://swcarpentry.github.io/r-novice-gapminder/10-functions/)  
[Tutorial: Write Functions](https://rstudio.cloud/learn/primers)

### Day 8 2/18
RMarkdown tutorials: [1](https://kbroman.org/knitr_knutshell/pages/Rmarkdown.html) and [2](https://kbroman.org/datacarpentry_R_2018-06-04/04-rmarkdown.html)  
[Tutorial: Iterate](https://rstudio.cloud/learn/primers)  
Read: [R For Data Science ch. 21.5, 25.2](https://r4ds.had.co.nz/)  

### Day 9 2/20


### Day 10 2/25  
[Shell materials](shell.html)  
[Software Carpentry Shell](http://swcarpentry.github.io/shell-novice/)  
Read: [Janssens](https://www.datascienceatthecommandline.com/) Welcome, Preface, ch. 1.0-1.5, 2.3.1-2.3.2

### Day 11 2/27
Read: [Janssens](https://www.datascienceatthecommandline.com/) ch. 5.2  
Read: Buffalo ch. 2, 3 (1st part)

### Day 12 3/3
Read: Buffalo ch. 3, (2nd part) 7 (1st part), 12  
Read: [Janssens](https://www.datascienceatthecommandline.com/) ch. 4.0-4.2.1 and 4.2.4-4.2.5

### Day 13 3/5
[Software Carpentry Shell Extras](https://carpentries-incubator.github.io/shell-extras/)  
Read: [Janssens](https://www.datascienceatthecommandline.com/) ch. 4.2.2  
Read: Buffalo ch. 12 (1st part)

### Day 14 3/24
Read: Buffalo ch. 12 (conditionals)  

### Day 15 3/26
[Sed and Awk](https://neurohackweek.github.io/advancedunix/01-first-part/)  
Read: Buffalo 7 (2nd part), 12 (2nd part)  
[Software Carpentry HPC Intro](https://hpc-carpentry.github.io/hpc-intro/)  
[HPC at URI](https://web.uri.edu/hpc-research-computing/)  
[HPC materials](hpc.html)

### Day 16 3/31
HPC

### Day 17 4/2
Git

### Day 18 4/7
Git

### Day 19 4/9
Python

### Day 20 4/14
Python

### Day 21 4/16
Python

### Day 22 4/21
Python

### Day 23 4/23
Python

### Day 24 4/28
Python



