---
title: "Schedule"
output: 
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
    theme: cosmo
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(kableExtra)
```

## Meeting Schedule

```{r, warning=FALSE}
Day <- c(1:24)
Date <- c("1/23", "1/28", "1/30", "2/4", "2/6", "2/11", "2/13", "2/18", "2/20", #R
          "2/25", "2/27", "3/3", "3/5", "3/24", #Shell
          "3/26", "3/31", "4/2", "4/7", #HPC/Git
          "4/9", "4/14", "4/16", "4/21", "4/23", "4/28")
Topic <- c("Intro", "Intro R and plots","Data manipulation","Tidy Data",
           "Tidy Data","Reproducible research", "Functions", "R Markdown", "Apply / mapping",
           "Intro Shell","Pipes and Loops","Scripts","Finding", "Permissions, Conditionals, Manipulation", 
           "HPC", "HPC", "Git", "Git", 
           "Intro Python", "Python","Scripting", "Functions", "Testing", "Open")

meetings <- cbind(Day, Date, Topic)

kable(meetings, "html") %>%  
  kable_styling(bootstrap_options = c("striped", "hover", "responsive"))
```
